[package]
name = "work"
version = "0.1.0"
edition = "2021"

[dependencies]
datafusion = "37.1.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_yaml = "0.9.34"
tokio =  { version = "1.43.0", features = ["full"] }

