[package]
name = "test01"
version = "0.1.0"
edition = "2021"

[dependencies]
datafusion = "44.0.0"  
tokio = { version = "1.43.0", features = ["full"] }
arrow = "44.0.0" 
uuid = { version = "1.3", features = ["v4"] }
chrono = "0.4"
deltalake = "0.8.0"